pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }

    stages {
        stage('Fetch code from VCS') {
            steps {
                git branch: 'ss-rem', url: 'https://github.com/QuadriDevOps1/sscademy_devops.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn install -DskipTests'
            }
            post {
                success {
                    echo 'Now archiving the artifact...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage('UNIT TEST') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Checkstyle analysis') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
        }

        stage('Sonar Analysis') {
            environment {
                scannerHome = tool 'sonar4.7'
            }
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sscademy \
                    -Dsonar.projectName=sscademy-repo \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=src/ \
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                    -Dsonar.junit.reportsPath=target/surefire-reports/ \
                    -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('UploadArtifact') {
            steps {
                nexusArtifactUploader(
                nexusVersion: 'nexus3',
                protocol: 'http',
                nexusUrl: '44.204.154.163:8081',
                groupId: 'DEV',
                version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                repository: 'sscademy-repo',
                credentialsId: 'nexuslogin',
                artifacts: [
                [artifactId: sscademy,
                classifier: '',
                file: '/target/sscademy-v2.war',
                type: 'war']
            ]
        )

            }
        }
        





















        stage('UploadArtifact') {
            steps {
                nexusArtifactUploader(
                nexusVersion: 'nexus3',
                protocol: 'http',
                nexusUrl: 'public_ip_of_nexus:8081',
                groupId: 'DEV',
                version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                repository: 'sscademy-repo',
                credentialsId: 'nexuslogin',
                artifacts: [
                    [artifactId: sscademyapp,
                    classifier: '',
                    file: 'target/sscademy-v2.war',
                    type: 'war']
                ]
             )

            }
        }
     }
}