apiVersion: apps/v1
kind: Deployment
metadata:
  name: sscademy-app
  labels: 
    app: sscademy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sscademy-app
  template:
    metadata:
      labels:
        app: sscademy-app
    spec:
      containers:
      - name: sscademy-app
        image: {{ .Values.appimage}}
        ports:
        - name: app-port
          containerPort: 8080
      # initContainers:
      # - name: init-mydb
      #   image: busybox
      #   command: ['sh', '-c', 'until nslookup sscademy-db; do echo waiting for mydb; sleep 2; done;']
      # - name: init-memcache
      #   image: busybox
      #   command: ['sh', '-c', 'until nslookup sscademy-cache01; do echo waiting for mydb; sleep 2; done;']
